use github-push-action

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -51,7 +51,7 @@ jobs:
     # Build a website based on the retrieved docstrings
     - name: Build Sphinx HTML
       run: |
-        sphinx-build -b singlehtml carmm/docs/source docs
+        sphinx-build -b html carmm/docs/source docs
 
     # tell GitHub not to use the Jekyll builder explicitly
     - - name: Prevent using Jekyll to use static files properly
@@ -64,3 +64,25 @@ jobs:
       with:
         name: DocumentationHTML
         path: docs/
+
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+    run: |
+      git clone https://github.com/logsdail/carmm.git --branch gh-pages --single-branch gh-pages
+      cp -r docs/_build/html/* gh-pages/
+      cd gh-pages
+      git config --local user.email "action@github.com"
+      git config --local user.name "GitHub Action"
+      git add .
+      git commit -m "Update documentation" -a || true
+      # The above command will fail if no changes were present, so we ignore
+      # that.
+
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+  # ===============================
